title: Collections
description: Generic collections library for Go
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default
url: https://khajamoddin.github.io/collections
repository: khajamoddin/collections
markdown: kramdown
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
search: true
logo: /assets/logo.svg
collections:
  v1:
    output: true
    permalink: /v1/:path/
  vNext:
    output: true
    permalink: /vNext/:path/
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
  - scope:
      path: "v1"
      type: "v1"
    values:
      layout: single
  - scope:
      path: "vNext"
      type: "vNext"
    values:
      layout: single
