title: Collections
description: Generic collections library for Go
theme: just-the-docs
url: https://khajamoddin.github.io/collections
repository: khajamoddin/collections
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
nav_order: 1
aux_links:
  Go Reference: https://pkg.go.dev/github.com/khajamoddin/collections
  Source on GitHub: https://github.com/khajamoddin/collections
just_the_docs:
  search_enabled: true
  nav_external_links:
    - title: Go Report Card
      url: https://goreportcard.com/report/github.com/khajamoddin/collections

